"""llama.cpp presets.ini management for the Web UI.

The *current* presets.ini is the file llama.cpp reads at runtime
(``~/.config/llama.cpp/presets.ini``). The *recommended* one is generated by
llama-autotune from the best configuration found by the optimizer, and stored
in the tool's data directory. The Web UI can show both and apply the
recommended over the current with a timestamped backup.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .models import SearchConfig


CURRENT_PRESETS_PATH = (
    Path.home() / ".config" / "llama.cpp" / "presets.ini"
)
RECOMMENDED_PRESETS_PATH = (
    Path.home() / ".llama-autotune" / "recommended-presets.ini"
)

_DEFAULT_HEADER = (
    "version = 1\n"
    "\n"
    "[*]\n"
    "n-gpu-layers = 99\n"
    "flash-attn = on\n"
)


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (FileNotFoundError, OSError):
        return ""


def current_content() -> str:
    """Return the current presets.ini content (empty if missing)."""
    return _read(CURRENT_PRESETS_PATH)


def recommended_content() -> str:
    """Return the generated recommended presets.ini (empty if missing)."""
    return _read(RECOMMENDED_PRESETS_PATH)


def config_to_ini_lines(config: SearchConfig) -> list[str]:
    """Convert a SearchConfig to presets.ini section lines."""
    lines: list[str] = []

    if config.n_gpu_layers is not None:
        lines.append(f"n-gpu-layers = {config.n_gpu_layers}")
    if config.ctx_size is not None:
        lines.append(f"ctx-size = {config.ctx_size}")
    if config.batch_size is not None:
        lines.append(f"batch-size = {config.batch_size}")
    if config.ubatch_size is not None:
        lines.append(f"ubatch-size = {config.ubatch_size}")
    if config.flash_attn is not None:
        lines.append(
            f"flash-attn = {'on' if config.flash_attn else 'off'}"
        )
    if config.cache_type_k:
        lines.append(f"cache-type-k = {config.cache_type_k}")
    if config.cache_type_v:
        lines.append(f"cache-type-v = {config.cache_type_v}")

    lines.append("load-on-startup = false")
    return lines


def _upsert_section(
    content: str,
    section: str,
    section_lines: list[str],
) -> str:
    """Replace (or append) an INI section while preserving the rest."""
    lines = content.splitlines()
    header = f"[{section}]"

    out: list[str] = []
    found = False
    i = 0

    while i < len(lines):
        line = lines[i]

        if line.strip() == header:
            out.append(header)
            out.extend(section_lines)
            found = True
            i += 1

            while i < len(lines) and not lines[i].strip().startswith("["):
                i += 1

            continue

        out.append(line)
        i += 1

    if not found:
        if out and out[-1].strip() != "":
            out.append("")
        out.append(header)
        out.extend(section_lines)

    return "\n".join(out) + "\n"


def generate_recommended(
    config: SearchConfig,
    model_path: str,
) -> str:
    """Generate and persist a recommended presets.ini from a best config.

    Takes the current presets.ini (or a default header) and updates the
    section for ``model_path`` with the supplied configuration.

    Args:
        config: The best configuration found by the optimizer.
        model_path: Path of the model the configuration belongs to.

    Returns:
        The generated presets.ini content.
    """
    current = current_content()
    if not current.strip():
        current = _DEFAULT_HEADER

    section = Path(model_path).stem
    content = _upsert_section(
        current,
        section,
        config_to_ini_lines(config),
    )

    RECOMMENDED_PRESETS_PATH.parent.mkdir(parents=True, exist_ok=True)
    RECOMMENDED_PRESETS_PATH.write_text(content, encoding="utf-8")

    return content


def apply_recommended() -> dict:
    """Back up the current presets and overwrite it with the recommended.

    Returns:
        A dict with the written path and the backup path (or ``None`` when
        no current file existed).

    Raises:
        FileNotFoundError: When no recommended file exists.
    """
    recommended = recommended_content()
    if not recommended.strip():
        raise FileNotFoundError(
            "Nessun presets.ini consigliato disponibile: "
            "esegui prima un'ottimizzazione."
        )

    backup = None
    current = current_content()
    if current.strip():
        stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        backup = Path(str(CURRENT_PRESETS_PATH) + f".bak-{stamp}")
        backup.write_text(current, encoding="utf-8")

    CURRENT_PRESETS_PATH.parent.mkdir(parents=True, exist_ok=True)
    CURRENT_PRESETS_PATH.write_text(recommended, encoding="utf-8")

    return {
        "written": str(CURRENT_PRESETS_PATH),
        "backup": str(backup) if backup is not None else None,
    }
